### ISSUE TITLE
Failing test from Mira package

### ISSUE THREAD

**Issue by feugy** [nearform/titus#636] opened 2020-12-01 14:56 UTC
### Reproduction steps and actual behavior

On a fresh clone, run all the tests:
```shell
git clone git@github.com:nearform/titus.git
cd titus
npm i
npm run create:env
npm run db:up
npm run test:all
```

Then you'll get errors from Mira package:
```shell
titus-infra-aws-mira: FAIL cdk/core/index.test.ts
titus-infra-aws-mira:   ● Test suite failed to run
titus-infra-aws-mira:     cdk/core/database.ts:51:7 - error TS2345: Argument of type '{ engine: IInstanceEngine; instanceType: InstanceType; vpc: IVpc; vpcPlacement: { subnetType: SubnetType.PUBLIC; }; storageEncrypted: false; ... 9 more ...; securityGroups: ISecurityGroup[]; }' is not assignable to parameter of type 'DatabaseInstanceProps'.
titus-infra-aws-mira:       Object literal may only specify known properties, and 'masterUsername' does not exist in type 'DatabaseInstanceProps'.
titus-infra-aws-mira:     51       masterUsername,
titus-infra-aws-mira:              ~~~~~~~~~~~~~~
titus-infra-aws-mira: FAIL cdk/api-gw-nlb/index.test.ts
```

(repeated several times)

### Expected behavior?

All tests should pass.

### Configuration

Running on Ubuntu 20.04.1, 64x, node 14.12

**Comment by simoneb** [comment] 2020-12-01 15:02
There is a chance that it may be related to upgrading package versions automatically. I have tried to be careful to avoid bumping packages which I knew would be causing issues, like the AWS CDK ones (you can see that reflected in the Renovate configuration), but I believe mira was upgraded by a minor version, for instance.

**Comment by irelandm** [comment] 2020-12-01 16:46
Yes, generally things break if there is *any* discrepancy with CDK versions

**Comment by simoneb** [comment] 2020-12-01 16:52
@irelandm there shouldn't be any discrepancies with cdk versions:

- the version of mira that's being used is [1.4.1](https://github.com/nearform/titus/blob/master/packages/titus-infra-aws-mira/package.json#L55)
- which [uses cdk 1.67.0](https://github.com/nearform/mira/blob/v1.4.1/package.json#L27)
- and titus [uses that too](https://github.com/nearform/titus/blob/master/packages/titus-infra-aws-mira/package.json#L32)
- and I made sure that Renovate [does not try to bump cdk](https://github.com/nearform/titus/blob/master/renovate.json#L15)

So I believe that is not the issue. The issue might be though that Mira was updated from 1.4.0 to 1.4.1 and CDK from (I believe) 1.62.0 to 1.67.0, which may be the issue.

**Comment by irelandm** [comment] 2020-12-01 16:55
Thanks Simone. I've asked Ron to look into it. He's new to Mira and probably Titus, but has time to explore it.

**Comment by irelandm** [comment] 2020-12-01 16:58
You can see the CDK version bumps for Mira here: https://github.com/nearform/mira/releases

**Comment by litzenberger** [comment] 2020-12-01 18:04
Was not able to recreate issue.  I had to add one more step and that was to `titus/packages/titus-frontend npm run build`
Once I did that all tests passed
```
titus-infra-aws-mira: Ran all test suites.
lerna success run Ran npm script 'test' in 4 packages in 279.4s:
lerna success - titus-backend
lerna success - titus-db-manager
lerna success - titus-frontend
lerna success - titus-infra-aws-mira
```

**Comment by feugy** [comment] 2020-12-03 10:16
Hello gents.

Sorry to bother, but I'm still having the issue:
- I dropped the node_modules
- fetch latest titus code
- installed dependencies
- ran `npm run build`: here is the outcome:
   ```js
   > titus-infra-aws-mira@1.0.0 build /home/damien/dev/nearform/titus/packages/titus-infra-aws-mira
   > tsc
   
   cdk/core/database.ts:51:7 - error TS2345: Argument of type '{ engine: IInstanceEngine; instanceType: InstanceType; vpc: IVpc; vpcPlacement: { subnetType: SubnetType.PUBLIC; }; storageEncrypted: false; ... 9 more ...; securityGroups: ISecurityGroup[]; }' is not assignable to parameter of type 'DatabaseInstanceProps'.
     Object literal may only specify known properties, and 'masterUsername' does not exist in type 'DatabaseInstanceProps'.
   
   51       masterUsername,
            ~~~~~~~~~~~~~~
   ```

Since in titus' [quick start guide](https://nf-titus.netlify.app/#/quick-start/) does not mention anything about building Mira, we should consider either changing it, or build after installing.

Running the tests is part of the user first experience with this accelerator. 
They probably don't know what Mira is about (kind of like me), and it is important to make them comfortable.

**Comment by simoneb** [comment] 2020-12-03 10:35
@feugy did you try a more typical lerna approach:

```
clone ...
lerna bootstrap
lerna run build
```

**Comment by feugy** [comment] 2020-12-03 10:44
I wasn't aware of it :sweat_smile:

But unfortunately, it doesn't work:
```shell
damien@XPS-UltraTitine ~/dev/nearform$ rm -rf titus/

damien@XPS-UltraTitine ~/dev/nearform$ git clone git@github.com:nearform/titus.git
Cloning into 'titus'...
remote: Enumerating objects: 54, done.
remote: Counting objects: 100% (54/54), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 10713 (delta 37), reused 38 (delta 28), pack-reused 10659
Receiving objects: 100% (10713/10713), 17.18 MiB | 13.19 MiB/s, done.
Resolving deltas: 100% (6793/6793), done.

damien@XPS-UltraTitine ~/dev/nearform$ cd titus/

damien@XPS-UltraTitine ~/dev/nearform/titus (master)$ npx lerna bootstrap
npx : 762 installé(s) en 20.804s
lerna notice cli v3.22.1
lerna info Bootstrapping 4 packages
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna info lifecycle titus-frontend@1.0.0-alpha.1~postinstall: titus-frontend@1.0.0-alpha.1

> titus-frontend@1.0.0-alpha.1 postinstall /home/damien/dev/nearform/titus/packages/titus-frontend
> patch-package

patch-package 6.2.2
Applying patches...
react-dev-utils@10.2.1 ✔
react-scripts@3.4.4 ✔
lerna success Bootstrapped 4 packages

damien@XPS-UltraTitine ~/dev/nearform/titus (master)$ npx lerna run build
npx : 762 installé(s) en 16.548s
lerna notice cli v3.22.1
lerna info Executing command in 2 packages: "npm run build"
lerna ERR! npm run build exited 1 in 'titus-frontend'
lerna ERR! npm run build stdout:

> titus-frontend@1.0.0-alpha.1 build /home/damien/dev/nearform/titus/packages/titus-frontend
> react-scripts build


lerna ERR! npm run build stderr:

There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "babel-loader": "8.1.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of babel-loader was detected higher up in the tree:

  /home/damien/dev/nearform/titus/packages/titus-frontend/node_modules/babel-loader (version: 8.2.2) 

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.

To fix the dependency tree, try following the steps below in the exact order:

  1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
  2. Delete node_modules in your project folder.
  3. Remove "babel-loader" from dependencies and/or devDependencies in the package.json file in your project folder.
  4. Run npm install or yarn, depending on the package manager you use.

In most cases, this should be enough to fix the problem.
If this has not helped, there are a few other things you can try:

  5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
     This may help because npm has known issues with package hoisting which may get resolved in future versions.

  6. Check if /home/damien/dev/nearform/titus/packages/titus-frontend/node_modules/babel-loader is outside your project directory.
     For example, you might have accidentally installed something in your home folder.

  7. Try running npm ls babel-loader in your project folder.
     This will tell you which other package (apart from the expected react-scripts) installed babel-loader.

If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That would permanently disable this preflight check in case you want to proceed anyway.

P.S. We know this message is long but please read the steps above :-) We hope you find them helpful!

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! titus-frontend@1.0.0-alpha.1 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the titus-frontend@1.0.0-alpha.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/damien/.npm/_logs/2020-12-03T10_41_01_601Z-debug.log

lerna ERR! npm run build exited 1 in 'titus-frontend'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.

```

For the sake of testing, I've removed the titus-frontend build scripts and retried:
```shell
damien@XPS-UltraTitine ~/dev/nearform/titus (master)$ npx lerna run build
npx : 762 installé(s) en 17.435s
lerna notice cli v3.22.1
lerna info Executing command in 1 package: "npm run build"
lerna ERR! npm run build exited 2 in 'titus-infra-aws-mira'
lerna ERR! npm run build stdout:

> titus-infra-aws-mira@1.0.0 build /home/damien/dev/nearform/titus/packages/titus-infra-aws-mira
> tsc

cdk/core/database.ts(51,7): error TS2345: Argument of type '{ engine: IInstanceEngine; instanceType: InstanceType; vpc: IVpc; vpcPlacement: { subnetType: SubnetType.PUBLIC; }; storageEncrypted: false; ... 9 more ...; securityGroups: ISecurityGroup[]; }' is not assignable to parameter of type 'DatabaseInstanceProps'.
  Object literal may only specify known properties, and 'masterUsername' does not exist in type 'DatabaseInstanceProps'.

lerna ERR! npm run build stderr:
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! titus-infra-aws-mira@1.0.0 build: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the titus-infra-aws-mira@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/damien/.npm/_logs/2020-12-03T10_44_10_774Z-debug.log

lerna ERR! npm run build exited 2 in 'titus-infra-aws-mira'
```

**Comment by simoneb** [comment] 2020-12-03 10:50
Ok so it may be two related issues. The reason why the frontend doesn't build is the version of babel-loader and for some reason it's getting a version it doesn't like. That's the first issue to solve. See if you have the SKIP_PREFLIGHT_CHECK in the frontend .env file, in theory that should work.

**Comment by feugy** [comment] 2020-12-03 11:08
I don't because I haven't run `lerna run create:env`, which creates the `.env` file so that we can build the frontend.

I'm playing dumb here: but if you say lerna users are used to bootstrap+build, then we'll have to make it work for them.

**Comment by simoneb** [comment] 2020-12-03 11:12
The setup instructions should be documented here https://nf-titus.netlify.app/#/quick-start/

**Comment by inigo-garcia** [comment] 2021-03-08 12:48
@feugy I've been trying to reproduce the bug but following the documentation and running similar commands as  @litzenberger , everything looks fine. Tests and CI ran OK.

**Comment by simoneb** [comment] 2021-03-08 12:58
@inigo-garcia in order to close this issue we need to make sure that CI runs the same commands that the quickstart shows and that this issue is about

**Comment by inigo-garcia** [comment] 2021-03-08 15:30
We have done a small improvement with the documentation to remark the importance of building the project before running the tests. 

Please, feel free to reopen the issue if you continue experiencing issues. We recommend to follow the documentation step by step and it should work as expected.

**Closed by inigo-garcia** 2021-03-08 15:30 UTC
Labels: Bug
